project:
  type: book
  output-dir: docs

book:
  title: "advanced-r"
  author: "Jane Doe"
  date: "7/9/2022"
  chapters:
    - index.qmd
    - ch02_namesvalues.qmd
    - ch03_vectors.qmd
    - test.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



