project:
  type: book
  output-dir: docs

book:
  title: "Advanced R Handbook"
  author: "Josh Livingston"
  date: "7/9/2022"
  chapters:
    - index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



