# https://github.com/quarto-dev/quarto-actions
name: Render and Publish Quarto Files
on:
  push:

jobs:
  quarto-render-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-renv@v2

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Render README
      run: quarto render README.qmd

    - name: Render Book
      uses: quarto-dev/quarto-actions/render@v2

    - name: Add & Commit changes
      uses: EndBug/add-and-commit@v9.0.1
      with:
        author_name: joshwlivingston
        author_email: joshwlivingston@gmail.com
        message: 'GH actions document render'
